export const pendaftaranActionTypes = {
    GET_PENDAFTARAN_SUCCESS: "GET_PENDAFTARAN_SUCCESS",
    GET_PENDAFTARAN_FAILED: "GET_PENDAFTARAN_FAILED",
    GET_PENDAFTARAN_REQUEST: "GET_PENDAFTARAN_REQUEST",
  
    CREATE_PENDAFTARAN_REQUEST: "CREATE_PENDAFTARAN_REQUEST",
    CREATE_PENDAFTARAN_SUCCESS: "CREATE_PENDAFTARAN_SUCCESS",
    CREATE_PENDAFTARAN_FAILED: "CREATE_PENDAFTARAN_FAILED",
  
    UPDATE_PENDAFTARAN_REQUEST: "UPDATE_PENDAFTARAN_REQUEST",
    UPDATE_PENDAFTARAN_SUCCESS: "UPDATE_PENDAFTARAN_SUCCESS",
    UPDATE_PENDAFTARAN_FAILED: "UPDATE_PENDAFTARAN_FAILED",
  
  
    DELETE_PENDAFTARAN_REQUEST: "DELETE_PENDAFTARAN_REQUEST",
    DELETE_PENDAFTARAN_SUCCESS: "DELETE_PENDAFTARAN_SUCCESS",
    DELETE_PENDAFTARAN_FAILED: "DELETE_PENDAFTARAN_FAILED",
  };